### ISSUE TITLE
Question: Fork for use with Emby

### ISSUE THREAD

**Issue by Beannsss** [RickDB/PlexAniSync#109]
This might not be the right spot for this, but this is my repo forked from this project: https://github.com/Beannsss/EmbyAniSync

A lot of code is unchanged (mainly on the anilist side), but most references to "plex" are changed to "emby". I'm not asking for a code review, I just have a few questions.

Is this okay?
Should I make this private only?
I probably have less than 8 hours of python experience as of this point, but would there be any interest in any kind of high quality PR in the future for adding Emby support to the main project? At the moment I kind of ripped all the plex side of it up and replaced it.

I apologize if I'm overstepping in any way. I'm a java developer and have little experience in contributing to open-sourced projects.

Thanks for this awesome project.

**Comment by Beannsss** [comment]
Just getting ahead of it I guess first priority would be to use a different anilist client ID

**Comment by reconman** [comment]
First of all, Github is all about forking and expanding/transforming existing projects.

That's why all Github repositories have copyleft licenses, which allow you to use the code for your own purposes. There are different licenses, the GPL v3.0 one used here allows you to do anything with the source code granted that you have a list of modifications (commit history) and publish your own source code.

If you're forking this repo, those 2 conditions usually aren't any issue. The main issue are companies which use open source code for their own pay-to-use applications while ignoring the license conditions.

I'd rather keep Emby separate from this repo, since the existing code is a bunch of spaghetti code and there's already an issue of maintaining the different parts of PlexAniSync. For example, the Docker containers are usually ignored by contributors.

Btw, when I tried out Jellyfin some time ago, I used the Trakt plugin instead and managed my Anilist changes manually. I also didn't want to invest too much time into developing something since I wasn't sure if I really want to switch from Plex to Jellyfin.

**Comment by Beannsss** [comment]
> First of all, Github is all about forking and expanding/transforming existing projects.
> 
> That's why all Github repositories have copyleft licenses, which allow you to use the code for your own purposes. There are different licenses, the GPL v3.0 one used here allows you to do anything with the source code granted that you have a list of modifications (commit history) and publish your own source code.
> 
> If you're forking this repo, those 2 conditions usually aren't any issue. The main issue are companies which use open source code for their own pay-to-use applications while ignoring the license conditions.
> 

Thanks for the response. I understood most of this about Github, but just wanted to check with the original repo just in case there was an issue with licensing as this repo is dealing with other potentially paid products (such as Plex) and I am dealing with another.

> I'd rather keep Emby separate from this repo, since the existing code is a bunch of spaghetti code and there's already an issue of maintaining the different parts of PlexAniSync. For example, the Docker containers are usually ignored by contributors.
> 

Makes 100% sense to me.

> Btw, when I tried out Jellyfin some time ago, I used the Trakt plugin instead and managed my Anilist changes manually. I also didn't want to invest too much time into developing something since I wasn't sure if I really want to switch from Plex to Jellyfin.
>

Yeah... I made the tentative change to Jellyfin and decided on Emby since they make networking and user management easy. The main reason for my move was the way Plex was the multitude of android app problems, like requiring a transcode for .ASS subtitles (Emby/JF added custom support for these formats to play direct) and playback issues when transcoding: https://forums.plex.tv/t/playback-hangs-near-end-of-file-after-ff-rw-pause-androidtv-client/710411/30

Thanks again.

**Comment by reconman** [comment]
Regarding Plex' shitty players, Kodi with a Plex plugin is the solution. Works well for TVs but has janky touch controls on phones.

**Comment by Beannsss** [comment]
Yeah I had that set up for a bit, and it was nice, but maybe it's more of a personal vendetta against plex's unwillingness to fix product-breaking bugs like what I mentioned, and implementing new playback features instead of adding Plex Arcade (wooo!).
