### ISSUE TITLE
Add remote-mappings as a Docker Environment Variable

### ISSUE THREAD

**Issue by cantnamethis** [RickDB/PlexAniSync#112]
Hello again, 
I really like the addition of remote-mappings in version 1.3.17, but I'd like having the remote-url as a environment variable, this way the custom_mappings could be shipped directly with the docker container itself, and not require an additional custom_mappings file to function.
Thanks.

**Comment by reconman** [comment]
Since it's a list and there may be more than one useful community mapping in the future, I'd rather let users configure the URLs themselves.

And often users have unmapped series in their library, so they have to create the file anyways. Or they only complain about missing mappings in the mapping repo instead of contributing with PRs.
