### ISSUE TITLE
I don't seem to understand this...

### ISSUE THREAD

**Issue by xPandaemonium** [RickDB/PlexAniSync#7]
Am I missing something? Because if I have to add each entry to AniList prior to Syncing from plex then that tells me that this is not the solution for me

Pretty sure I put in the anime_section variable correctly and even tried using the plex media scanner to use the section ID...

```
2019-08-04 01:21:18 [MAPPING] Custom map file not found: custom_mappings.ini
2019-08-04 01:21:18 AniList skip list update enabled in settings, will match but NOT update your list
2019-08-04 01:21:18 [ANILIST] Retrieving AniList list for user: xPandaemonium
2019-08-04 01:21:19 [ANILIST] Found 0 anime series on list
2019-08-04 01:21:19 No items found on your AniList list to process
2019-08-04 01:21:19 Plex to AniList sync finished
```

**Comment by RickDB** [comment]
Checking this now as it might be that you need at least one item on your AniList list before it continues.

**Comment by RickDB** [comment]
Should be fixed now 👍

**Comment by xPandaemonium** [comment]
Ok, thank you. I'll give it a shot!

**Comment by xPandaemonium** [comment]
So there is definitely some progress but this seems like a separate issue. I can't seem to identify if / what the issue on my server side, according to the logs.

I know for a fact that the username is correct and my email does not seem to work in its place.
```
2019-08-06 14:19:23 [MAPPING] Custom map file not found: custom_mappings.ini
2019-08-06 14:19:23 AniList skip list update enabled in settings, will match but NOT update your list
2019-08-06 14:19:23 [ANILIST] Retrieving AniList list for user: xPandaemonium
2019-08-06 14:19:23 [ANILIST] Found 0 anime series on list
2019-08-06 14:19:23 No items found on your AniList list for additional processing later on
2019-08-06 14:19:23 Authenticating as admin for MyPlex home user: xPandaemonium
2019-08-06 14:19:24 Retrieving home user information
2019-08-06 14:19:25 Error occured during Plex Home user lookup or server authentication: Unable to find user xPandaemonium
2019-08-06 14:19:25 Unable to authenticate to Plex Media Server, traceback: local variable 'plex' referenced before assignment
2019-08-06 14:19:25 Plex authentication failed, check access to your Plex Media Server and settings
2019-08-06 14:19:25 Found no Plex shows for processing
2019-08-06 14:19:25 Found no watched shows on Plex for processing
2019-08-06 14:19:25 Plex to AniList sync finished
```

**Comment by RickDB** [comment]
Are you authenticating for another home user on the Plex server?

**Comment by xPandaemonium** [comment]
Not sure I follow, The server is mine and is on my current PC. There are 2 users being a family member and I. I would like to track watch data for only 1 of the users.
I have used the Trakt addon and ran into issues with series I have not watched being updated.

**Comment by RickDB** [comment]
If the user you are trying to sync is the Plex admin best to disable home_user_sync as it's only meant for users added to Plex home.

**Comment by RickDB** [comment]
Updated the readme for the home user syncing part a bit. 
To be clear you only need to enable home user syncing if you want to update an AniList list with data from a different Plex family / home user account.

**Comment by xPandaemonium** [comment]
Ok. thank you again, that did not seem clear to me but I wouldn't be surprised if I overlooked something. 😆 

It seems to be working now!

**Comment by RickDB** [comment]
That part could be misunderstood easily tbh so should be clearer for new users now as well.

Glad to hear it's working 👍

**Comment by xPandaemonium** [comment]
I was going to add this as a seperate issue but I just typed all this up and then realized what custom mapping was for 😅 but I still want to complain a bit lol 

If / Until this issue can be fixed, perhaps a band-aid would be export a .txt including the names of skipped titles to the script directory or something to that effect?
Would have saved me from going through the logs for over 200 items, aha.

Damn this is a mess.
I ain't much of a programmer but Is there anyway to help contribute to the custom_mappings.ini  for these odd entries? or do you intend on keeping it as a per-user kinda thing?

I know I would not want to manually update these on my own as the seasons go by, Jesus.

It seems that titles who's years do not match are skipped from updating, which is understandable.
I can only guess that it's due to some of these shows having separate seasons as their own entry.

Attack on Titan being a rather egregious example with it's Season 3 & Season 3 Part 2 bullshit.

Examples:
Season 1 = Updated 
Season 2 = Skipped
`[ANILIST] Series year did not match (skipping update) => Plex has 2013 and AniList has 2017`
Season 3 = Skipped
`[ANILIST] Series year did not match (skipping update) => Plex has 2013 and AniList has 2018`

Honestly, I feel AniList should have a better way of managing this. like a absolute series entry...
I believe Plex took the right action lumping them together but  ¯\_(ツ)_/¯

List of offenders from my library:
---

I believe Little Witch Academia is messing up due to it's movie and TV release being separate.
Parasyte simply needs to be named as "Parasyte -the maxim-" in the search names.

```
Aggretsuko
Assassination Classroom
Attack on Titan
KONOSUBA -God's blessing on this wonderful world!
Little Witch Academia
Mob Psycho 100
My Hero Academia
One-punch Man
Overlord
Parasyte
Space Dandy
Sword Art Online
Tokyo Ghoul
```

**Comment by RickDB** [comment]
The year matching is so we don't get false positives as that's the only metadata Plex gives us except for the show name, to improve the matching if you aren't already using try the HAMA agent:

https://github.com/ZeroQI/Hama.bundle

This makes sure your Anime library is closer to Anidb and TVDB and my experience that it improves the AniList matching.

Sometimes AniList has a different started year (either from AniDB or contributors) which we don't really have a good solution for as Plex supplies with very little data for additional matching, a global AniList <--> Plex custom mapping file could work but need maintainers then and considering our relative small userbase might not be doable soon :)

We already do fuzzy matching for season formats like for My Hero Academia and such which matches for my library here, the season formats we use for cross matching right now:

<series name> <season number> <-- traditional naming
<series name> <roman numerals> <-- like for instance with SAO
<series name> season <season number> <-- like for instance My Hero Academia
<series name> 1st / 2nd 3rd etc.. season <-- ordinal season matching
<series name> 1st / 2nd 3rd etc.. thread<-- ordinal season matching alternative naming

So if the show has proper season structure in Plex it will match and we skip the start date matching for 2nd / 3rd season and so on, if they are split as separate entries within Plex as well because the name and start date will line up.
