### ISSUE TITLE
Latest version not available on Docker Hub

### ISSUE THREAD

**Issue by rg9400** [RickDB/PlexAniSync#84]
I noticed there was a new version published two days ago with a ton of nice updates, but it doesn't seem like Docker Hub has the latest image? Not sure if the repo changed or the build failed. Latest version on GH says 1.3.15, but I see DH only has 1.3.13

https://hub.docker.com/r/rickdb/plexanisync

**Comment by RickDB** [comment]
Yeah we moved away from Docker hub due to their new license restrictions (no auto builds being one):

https://www.docker.com/blog/updating-product-subscriptions/

You can find the new Docker location here which uses Github packages here:

https://github.com/RickDB/Docker-PlexAniSync/pkgs/container/plexanisync

For updates also post on the AniList forums especially for breaking changes like this so can always subscribe to it:

https://anilist.co/forum/thread/6443

**Comment by mizz141** [comment]
@rg9400 
I've made an updated version by pulling it from github and uploading it to the hub, you can get it here: https://hub.docker.com/repository/docker/mizz141/plexanisync-mizz141

**Comment by RickDB** [comment]
Like mentioned before our project is located fully on Github so @rg9400 can use the Github packages docker images which are always up to date with latest changes and maintained by our team.
Any Docker Hub version is no longer maintained or endorsed by us.

https://github.com/RickDB/PlexAniSync/pkgs/container/plexanisync
